# Generated by Django 5.2.5 on 2025-08-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_ai', '0002_interviewsession_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='total_questions',
            field=models.IntegerField(default=5),
        ),
    ]
